# Generated by Django 2.2.3 on 2019-12-04 14:37

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(upload_to='banner', verbose_name='轮播图片'),
        ),
    ]
