# Generated by Django 2.2.3 on 2020-01-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodscategory_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_logo',
            field=models.ImageField(blank=True, default='', help_text='分类logo', max_length=200, null=True, upload_to='category_logo/', verbose_name='分类logo'),
        ),
    ]
