# Generated by Django 2.2.3 on 2020-01-16 17:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200115_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=stdimage.models.StdImageField(upload_to='brands/', verbose_name='品牌图片'),
        ),
    ]
