# Generated by Django 2.2.3 on 2019-07-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190713_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('TRADE_CANCEL', '取消'), ('TRADE_PAYING', '待支付')], default='TRADE_PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
